CREATE DOMAIN DBLPRECISION AS DOUBLE PRECISION;

CREATE DOMAIN DDATE AS DATE;

CREATE DOMAIN INDEKSY AS INTEGER NOT NULL;

CREATE DOMAIN VKOD AS VARCHAR(15) CHARACTER SET NONE;

CREATE DOMAIN VDESC AS VARCHAR(100) CHARACTER SET NONE;
