CREATE TABLE FAKTURA (
    FAKTURA_ID INDEKSY,
    KLIENT_ID INDEKSY,
    FAKTURA_NUMER VKOD,
    KWOTA DBLPRECISION
);

CREATE TABLE IBE$VERSION_HISTORY (
    IBE$VH_ID INTEGER NOT NULL,
    IBE$VH_MODIFY_DATE TIMESTAMP NOT NULL,
    IBE$VH_USER_NAME VARCHAR(67) CHARACTER SET NONE,
    IBE$VH_OBJECT_TYPE SMALLINT NOT NULL,
    IBE$VH_OBJECT_NAME VARCHAR(67) CHARACTER SET NONE NOT NULL,
    IBE$VH_HEADER BLOB,
    IBE$VH_BODY BLOB,
    IBE$VH_CLIENT_ADDRESS VARCHAR(32) CHARACTER SET NONE,
    IBE$VH_DESCRIPTION BLOB SUB_TYPE TEXT
);

-- MAGAZYN: całkiem inna struktura (inna ilość i nazwy kolumn, inne domeny)
CREATE TABLE MAGAZYN (
    MAGAZYN_ID INDEKSY,
    MAGAZYN_KOD VKOD,
    LOKALIZACJA VDESC,
    CZY_AKTYWNY SMALLINT,
    DATA_UTWORZENIA DDATE
);

-- TOWAR: ta sama nazwa, 5 kolumn, ale inna domena na OPIS
CREATE TABLE TOWAR (
    TOWAR_ID INDEKSY,
    TOWAR_KOD VKOD,
    TOWAR_OPIS VDESC,        -- w A jest VOPIS
    STAN_MAG DBLPRECISION,
    MAGAZYN_ID INDEKSY
);

-- ZAMOWIENIE: identyczne jak w A
CREATE TABLE ZAMOWIENIE (
    ZAMOWIENIE_ID INDEKSY,
    KLIENT_ID INDEKSY,
    DATA_ZAM DDATE,
    KWOTA DBLPRECISION,
    STATUS VKOD
);

-- LOG_OPERACJI: dodatkowa tabela, której nie ma w A
CREATE TABLE LOG_OPERACJI (
    LOG_ID INDEKSY,
    DATA_OPERACJI DDATE,
    UZYTKOWNIK VKOD,
    OPIS VDESC,
    ZRODLO VKOD
);
