SET TERM ^ ;

-- ===============================
-- STUBY – puste ciała procedur
-- ===============================

CREATE OR ALTER PROCEDURE PODSUMUJ_FAKTURY_KLIENTA
(
    I_KLIENT_ID INDEKSY,
    I_CALL_OTHER SMALLINT = 1
)
RETURNS (
    SUMA_KWOT DBLPRECISION,
    ILE_FAKTUR INDEKSY
)
AS
BEGIN
END
^

CREATE OR ALTER PROCEDURE PRZEGLAD_FAKTUR_KLIENTA
(
    I_KLIENT_ID INDEKSY,
    I_MIN_KWOTA DBLPRECISION,
    I_CALL_OTHER SMALLINT = 1
)
RETURNS (
    FAKTURA_ID INDEKSY,
    KWOTA DBLPRECISION
)
AS
BEGIN
END
^

CREATE OR ALTER PROCEDURE PROC_MAG_OPIS
(
    I_MAGAZYN_ID INDEKSY
)
RETURNS (
    MAG_OPIS VDESC
)
AS
BEGIN
END
^

CREATE OR ALTER PROCEDURE PROC_TOWAR_Z_MAGAZYNU
(
    I_TOWAR_ID INDEKSY
)
RETURNS (
    TOWAR_KOD VKOD,
    MAGAZYN_OPIS VDESC
)
AS
BEGIN
END
^

CREATE OR ALTER PROCEDURE PROC_ZESTAWIENIE_KLIENTA
(
    I_KLIENT_ID INDEKSY
)
RETURNS (
    SUMA DBLPRECISION,
    ILOSC INDEKSY
)
AS
BEGIN
END
^

-- ===============================
-- WŁAŚCIWE CIAŁA PROCEDUR
-- ===============================

ALTER PROCEDURE PODSUMUJ_FAKTURY_KLIENTA
(
    I_KLIENT_ID INDEKSY,
    I_CALL_OTHER SMALLINT = 1
)
RETURNS (
    SUMA_KWOT DBLPRECISION,
    ILE_FAKTUR INDEKSY
)
AS
DECLARE VARIABLE V_FAKTURA_ID  INDEKSY;
DECLARE VARIABLE V_KWOTA       DBLPRECISION;
DECLARE VARIABLE V_TMP_FAK_ID  INDEKSY;
DECLARE VARIABLE V_TMP_KWOTA   DBLPRECISION;
BEGIN
  SUMA_KWOT  = 0;
  ILE_FAKTUR = 0;

  FOR
    SELECT
      FAKTURA_ID,
      KWOTA
    FROM FAKTURA
    WHERE KLIENT_ID = :I_KLIENT_ID
    INTO :V_FAKTURA_ID, :V_KWOTA
  DO
  BEGIN
    SUMA_KWOT  = SUMA_KWOT + V_KWOTA;
    ILE_FAKTUR = ILE_FAKTUR + 1;
  END

  IF (I_CALL_OTHER = 1 AND ILE_FAKTUR > 0) THEN
  BEGIN
    EXECUTE PROCEDURE PRZEGLAD_FAKTUR_KLIENTA(
      :I_KLIENT_ID,
      :SUMA_KWOT / :ILE_FAKTUR,
      0
    )
    RETURNING_VALUES
      :V_TMP_FAK_ID,
      :V_TMP_KWOTA;
  END

  SUSPEND;
END
^

ALTER PROCEDURE PRZEGLAD_FAKTUR_KLIENTA
(
    I_KLIENT_ID INDEKSY,
    I_MIN_KWOTA DBLPRECISION,
    I_CALL_OTHER SMALLINT = 1
)
RETURNS (
    FAKTURA_ID INDEKSY,
    KWOTA DBLPRECISION
)
AS
DECLARE VARIABLE V_SUM_KWOT DBLPRECISION;
DECLARE VARIABLE V_ILE_FAKTUR INDEKSY;
DECLARE VARIABLE V_LOCAL_FLAG SMALLINT;
BEGIN
  V_LOCAL_FLAG = I_CALL_OTHER;

  FOR
  SELECT
    F.FAKTURA_ID,
    F.KWOTA
  FROM FAKTURA F
  WHERE
    F.KLIENT_ID = :I_KLIENT_ID AND
    F.KWOTA >= :I_MIN_KWOTA
  INTO
    :FAKTURA_ID,
    :KWOTA
  DO
  BEGIN
    IF (V_LOCAL_FLAG = 1) THEN
    BEGIN
      EXECUTE PROCEDURE PODSUMUJ_FAKTURY_KLIENTA(:I_KLIENT_ID,
                                                 0)
          RETURNING_VALUES :V_SUM_KWOT,
                           :V_ILE_FAKTUR;

      V_LOCAL_FLAG = 0;
    END

    SUSPEND;
  END
END
^

ALTER PROCEDURE PROC_MAG_OPIS
(
    I_MAGAZYN_ID INDEKSY
)
RETURNS (
    MAG_OPIS VDESC
)
AS
BEGIN
  MAG_OPIS = NULL;

  SELECT
      CAST(M.MAGAZYN_KOD || ' ' || M.LOKALIZACJA AS VDESC)
  FROM MAGAZYN M
  WHERE M.MAGAZYN_ID = :I_MAGAZYN_ID
  INTO :MAG_OPIS;

  SUSPEND;
END
^

ALTER PROCEDURE PROC_TOWAR_Z_MAGAZYNU
(
    I_TOWAR_ID INDEKSY
)
RETURNS (
    TOWAR_KOD VKOD,
    MAGAZYN_OPIS VDESC
)
AS
DECLARE VARIABLE V_MAG_ID INDEKSY;
BEGIN
  TOWAR_KOD = NULL;
  MAGAZYN_OPIS = NULL;
  V_MAG_ID = NULL;

  SELECT
      T.TOWAR_KOD,
      T.MAGAZYN_ID
  FROM TOWAR T
  WHERE T.TOWAR_ID = :I_TOWAR_ID
  INTO
      :TOWAR_KOD,
      :V_MAG_ID;

  IF (V_MAG_ID IS NOT NULL) THEN
  BEGIN
    EXECUTE PROCEDURE PROC_MAG_OPIS(:V_MAG_ID)
      RETURNING_VALUES :MAGAZYN_OPIS;
  END

  SUSPEND;
END
^

ALTER PROCEDURE PROC_ZESTAWIENIE_KLIENTA
(
    I_KLIENT_ID INDEKSY
)
RETURNS (
    SUMA DBLPRECISION,
    ILOSC INDEKSY
)
AS
DECLARE VARIABLE V_FA_ID INDEKSY;
DECLARE VARIABLE V_KWOTA DBLPRECISION;
BEGIN
  SUMA = 0;
  ILOSC = 0;

  -- łączna suma i ilość z oryginalnej procedury
  EXECUTE PROCEDURE PODSUMUJ_FAKTURY_KLIENTA(:I_KLIENT_ID, 0)
    RETURNING_VALUES :SUMA, :ILOSC;

  -- dodatkowy "obrót" po fakturach z drugiej procedury
  FOR
    SELECT
      FAKTURA_ID,
      KWOTA
    FROM PRZEGLAD_FAKTUR_KLIENTA(:I_KLIENT_ID, 0, 0)
    INTO :V_FA_ID, :V_KWOTA
  DO
  BEGIN
    IF (:V_KWOTA > 0) THEN
    BEGIN
      -- udajemy bardziej zagmatwany kod
      SUMA = SUMA + 0;
    END
  END

  SUSPEND;
END
^

SET TERM ; ^
