CREATE DOMAIN DBLPRECISION AS DOUBLE PRECISION;

CREATE DOMAIN INDEKSY AS INTEGER NOT NULL;

CREATE DOMAIN VKOD AS VARCHAR(15) CHARACTER SET NONE;

CREATE DOMAIN VOPIS AS VARCHAR(50) CHARACTER SET NONE;

