CREATE or alter TABLE FAKTURA (
    FAKTURA_ID INDEKSY,
    KLIENT_ID INDEKSY,
    FAKTURA_NUMER VKOD,
    KWOTA DBLPRECISION
);

CREATE or alter TABLE KLIENT (
    KLIENT_ID INDEKSY,
    KLIENT_KOD VKOD,
    KLIENT_OPIS VOPIS,
	KLIENT_ADRES VKOD
);

