CREATE TABLE FAKTURA (
    FAKTURA_ID INDEKSY,
    KLIENT_ID INDEKSY,
    FAKTURA_NUMER VKOD,
    KWOTA DBLPRECISION
);

CREATE TABLE KLIENT (
    KLIENT_ID INDEKSY,
    KLIENT_KOD VKOD,
    KLIENT_OPIS VOPIS
);

