SET TERM ^ ;
CREATE OR ALTER PROCEDURE PRZEGLAD_FAKTUR
RETURNS (
	fak_id indeksy,
    FAKTURA_NUMER vkod,
    KWOTA DBLPRECISION,
    KLIENT_KOD VKOD,
    KLIENT_OPIS VOPIS
)
AS
BEGIN
  FOR
  SELECT
	faktura.faktura_id,
    FAKTURA.FAKTURA_NUMER,
    FAKTURA.KWOTA,
    KLIENT.KLIENT_KOD,
    KLIENT.KLIENT_OPIS
  FROM FAKTURA
  INNER JOIN KLIENT ON FAKTURA.KLIENT_ID = KLIENT.KLIENT_ID
  INTO
	:fak_id,
    :FAKTURA_NUMER,
    :KWOTA,
    :KLIENT_KOD,
    :KLIENT_OPIS
  DO
  BEGIN
    SUSPEND;
  END

END
^

SET TERM ; ^
