SET TERM ^ ;

-- === Stub definitions ===
CREATE OR ALTER PROCEDURE PODSUMUJ_FAKTURY_KLIENTA
(
    I_KLIENT_ID INDEKSY,
    I_CALL_OTHER SMALLINT = 1
)
RETURNS (
    SUMA_KWOT DBLPRECISION,
    ILE_FAKTUR INDEKSY
)
AS
BEGIN
END
^

CREATE OR ALTER PROCEDURE PRZEGLAD_FAKTUR_KLIENTA
(
    I_KLIENT_ID INDEKSY,
    I_MIN_KWOTA DOUBLE PRECISION,
    I_CALL_OTHER SMALLINT = 1
)
RETURNS (
    FAKTURA_ID INDEKSY,
    KWOTA DBLPRECISION
)
AS
BEGIN
END
^

-- === Full bodies ===
ALTER PROCEDURE PODSUMUJ_FAKTURY_KLIENTA
(
    I_KLIENT_ID INDEKSY,
    I_CALL_OTHER SMALLINT = 1
)
RETURNS (
    SUMA_KWOT DBLPRECISION,
    ILE_FAKTUR INDEKSY
)
AS
DECLARE VARIABLE V_FAKTURA_ID  INDEKSY;
DECLARE VARIABLE V_KWOTA       DBLPRECISION;
DECLARE VARIABLE V_TMP_FAK_ID  INDEKSY;
DECLARE VARIABLE V_TMP_KWOTA   DBLPRECISION;
BEGIN
  SUMA_KWOT  = 0;
  ILE_FAKTUR = 0;

  FOR
    SELECT
      FAKTURA_ID,
      KWOTA
    FROM FAKTURA
    WHERE KLIENT_ID = :I_KLIENT_ID
    INTO :V_FAKTURA_ID, :V_KWOTA
  DO
  BEGIN
    SUMA_KWOT  = SUMA_KWOT + V_KWOTA;
    ILE_FAKTUR = ILE_FAKTUR + 1;
  END

  IF (I_CALL_OTHER = 1 AND ILE_FAKTUR > 0) THEN
  BEGIN
    EXECUTE PROCEDURE PRZEGLAD_FAKTUR_KLIENTA(
      :I_KLIENT_ID,
      :SUMA_KWOT / :ILE_FAKTUR,
      0
    )
    RETURNING_VALUES
      :V_TMP_FAK_ID,
      :V_TMP_KWOTA;
  END

  SUSPEND;
END
^

ALTER PROCEDURE PRZEGLAD_FAKTUR_KLIENTA
(
    I_KLIENT_ID INDEKSY,
    I_MIN_KWOTA DOUBLE PRECISION,
    I_CALL_OTHER SMALLINT = 1
)
RETURNS (
    FAKTURA_ID INDEKSY,
    KWOTA DBLPRECISION
)
AS
DECLARE VARIABLE V_SUM_KWOT DBLPRECISION;
DECLARE VARIABLE V_ILE_FAKTUR INDEKSY;
DECLARE VARIABLE V_LOCAL_FLAG SMALLINT;
BEGIN
  V_LOCAL_FLAG = I_CALL_OTHER;

  FOR
  SELECT
    F.FAKTURA_ID,
    F.KWOTA
  FROM FAKTURA F
  WHERE
    F.KLIENT_ID = :I_KLIENT_ID AND
    F.KWOTA >= :I_MIN_KWOTA
  INTO
    :FAKTURA_ID,
    :KWOTA
  DO
  BEGIN
    IF (V_LOCAL_FLAG = 1) THEN
    BEGIN
      EXECUTE PROCEDURE PODSUMUJ_FAKTURY_KLIENTA(:I_KLIENT_ID,
                                                 0)
          RETURNING_VALUES :V_SUM_KWOT,
                           :V_ILE_FAKTUR;

      V_LOCAL_FLAG = 0;
    END

    SUSPEND;
  END
END
^

SET TERM ; ^
